credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Github creds"
          id: "ghusertoken"
          password: ${GITHUB_TOKEN}
          scope: GLOBAL
          # TODO get this from env var
          username: "tiannaru"
      - string:
          description: "gh token"
          id: "ghtoken"
          scope: GLOBAL
          secret: ${GITHUB_TOKEN}
      - usernamePassword:
          id: "dockertoken"
          password: ${DOCKER_TOKEN}
          scope: GLOBAL
          username: "${DOCKER_USER}"
jenkins:
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Credentials/Create:authenticated"
      - "GROUP:Credentials/Update:authenticated"
      - "GROUP:Job/Build:authenticated"
      - "GROUP:Job/Cancel:authenticated"
      - "GROUP:Job/Configure:authenticated"
      - "GROUP:Job/Create:authenticated"
      - "GROUP:Job/Delete:authenticated"
      - "GROUP:Job/Read:authenticated"
      - "GROUP:Job/Workspace:authenticated"
      - "GROUP:Overall/Read:authenticated"
      - "GROUP:Run/Delete:authenticated"
      - "GROUP:Run/Update:authenticated"
      - "GROUP:View/Configure:authenticated"
      - "GROUP:View/Create:authenticated"
      - "GROUP:View/Read:authenticated"
      - "USER:Overall/Administer:${JENKINS_ADMIN_ID}"
      - "USER:Job/Read:anonymous"
      - "USER:Overall/Read:anonymous"
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      templates:
      - containers:
        - image: "tiannaru/python-ci:latest"
          alwaysPullImage: true
          args: ""
          command: ""
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          workingDir: "/home/jenkins/agent"
        id: "1f12c900-5086-4384-ac7b-99b1442c5b72"
        label: "python-ci"
        name: "kube-agent"
        namespace: "jenkins"
        nodeUsageMode: NORMAL
        yamlMergeStrategy: "override"
        serviceAccount: "jenkins-admin"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: ${JENKINS_URL}
  githubpluginconfig:
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "ghtoken"
      manageHooks: true
jobs:
- file: /var/jenkins_home/jobs.groovy
