credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "Github creds"
          id: "ghusertoken"
          password: ${GITHUB_TOKEN}
          scope: GLOBAL
          username: "tiannaru"
      - string:
          description: "gh token"
          id: "ghtoken"
          scope: GLOBAL
          secret: ${GITHUB_TOKEN}
jenkins:
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      u;Fsers:
      - id: "admin"
        name: "admin"
        properties:
        - "apiToken"
        - "mailer"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://172.17.0.1:50000"
        readTimeout: 60
      name: "docker"
      templates:
      - labelString: "ci-python"
        connector: "attach"
        dockerTemplateBase:
          image: "tiannaru/python-lint:latest"
          cpuPeriod: 0
          cpuQuota: 0
      - labelString: "cd"
        connector: "attach"
        dockerTemplateBase:
          image: "tiannaru/alpine-cd:latest"
          cpuPeriod: 0
          cpuQuota: 0
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: ${JENKINS_URL}
  githubpluginconfig:
    configs:
    - name: "InHouse GitHub EE"
      apiUrl: "https://github.domain.local/api/v3"
      credentialsId: "ghtoken"
      manageHooks: true
jobs:
- file: /var/jenkins_home/jobs.groovy
